### ISSUE TITLE
Add another scaling algorithm to evenly distribute the value space

### ISSUE THREAD

**Issue by nreese** [nreese/enhanced_tilemap#22]
Dynamic Range bins are [generated](https://github.com/nreese/enhanced_tilemap/blob/4.x/public/vislib/marker_types/base_marker.js#L330) from a d3.js quantize scale, evenly dividing the aggregation metric result space (value space) into 1, 3, or 5 bins.

This does not provide very useful binning when the value space is not evenly distributed. In such cases, the majority of aggregation grid cells will be visualized with identical styling. 

Another binning algorithm should be provided that dynamically sizes bins based on distribution. Bins with lots of geogrid-cells should be made smaller. Bins with little geogrid-cells should be made larger. The algorithm should produce uneven bin widths that do a better job of evenly distributing the value space.

Users should be able to select this binning algorithm with the `Options -> Aggregations Options -> Quantize scale type` select input. The input should have three options; dynamic - even width bins, dynamic - even distribution, and static. Please change the names of the input and options to something that makes more sense.

**Comment by JacobBrandt** [comment]
I have another approach to this let me know what you think.

Instead of adding more stops in the threshold for our higher distribution areas we change the legend color to a linear scale.  So now we’ll have a lot more variance in color across the entire value space, and not just the higher distribution areas.  You’ll be able to see the progression between the 5 bands instead of it being discretely tied to a value range.

**Comment by nreese** [comment]
I am not sure if a linear scale would help since many colors would still look very similar when the results are extremely unevenly distributed.

This feature request should not add additional bins. The intent of the request is to just modify the boundaries of the current bins.

**Comment by JacobBrandt** [comment]
Got it, I know what you mean now.
